spring:
  application:
    name: api
  data:
    redis:
      host: localhost
      port: 16379

  datasource:
    url: jdbc:mysql://localhost:13306/webChat?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
      minimum-idle: 3
      maximum-pool-size: 6
      idle-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  jooq:
    sql-dialect: mysql

server:
  port: 8080