spring:
  application:
    name: api
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: 8080